import type { Metadata } from 'next'
import { Russo_One, Space_Grotesk } from 'next/font/google'
import Footer from './(components)/Footer'
import Header from './(components)/Header'
import './globals.css'
import { Providers } from './providers'

const grotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-sans',
})

const russo = Russo_One({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-russo',
})

export const metadata: Metadata = {
  title: 'TDA-consulting-trade - oil&gas trade',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${grotesk.variable} ${russo.variable}`}>
        <Providers>
          <main className='h-full bg-white bg-noise bg-cover'>
            <Header />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  )
}
